classdef ConfigInspector
    %CONFIGINSPECTOR Introspect config schema for dynamic UI generation.
    % Provides metadata about config fields including types, defaults,
    % constraints, and dropdown choices.

    methods (Static)
        function schema = getSchema()
            %GETSCHEMA Return struct array describing all config fields.
            % Each entry contains: path, type, default, constraints, choices, label, section

            persistent cached
            if ~isempty(cached)
                schema = cached;
                return;
            end

            cfg = tribe.Config.default();
            schema = struct('path', {}, 'type', {}, 'default', {}, ...
                'constraints', {}, 'choices', {}, 'label', {}, ...
                'section', {}, 'description', {}, 'units', {});

            % rack_profile section
            schema(end+1) = tribe.ui.ConfigInspector.makeField('rack_profile.chipset', ...
                'enum', cfg.rack_profile.chipset, '', ...
                tribe.ui.ConfigInspector.getChoices('rack_profile.chipset'), ...
                'Chipset', 'rack_profile', 'GPU hardware selection', '');

            schema(end+1) = tribe.ui.ConfigInspector.makeField('rack_profile.cooling_method', ...
                'enum', cfg.rack_profile.cooling_method, '', ...
                tribe.ui.ConfigInspector.getChoices('rack_profile.cooling_method'), ...
                'Cooling Method', 'rack_profile', 'Thermal management approach', '');

            schema(end+1) = tribe.ui.ConfigInspector.makeField('rack_profile.module_it_capacity_target_kw', ...
                'numeric', cfg.rack_profile.module_it_capacity_target_kw, 'positive', ...
                [], 'Module IT Capacity Target', 'rack_profile', 'Target IT power per module', 'kW');

            schema(end+1) = tribe.ui.ConfigInspector.makeField('rack_profile.electricity_price_gbp_per_kwh', ...
                'numeric', cfg.rack_profile.electricity_price_gbp_per_kwh, 'non_negative', ...
                [], 'Electricity Price', 'rack_profile', 'Electricity cost rate', 'GBP/kWh');

            schema(end+1) = tribe.ui.ConfigInspector.makeField('rack_profile.annual_operating_hours', ...
                'numeric', cfg.rack_profile.annual_operating_hours, 'positive', ...
                [], 'Annual Operating Hours', 'rack_profile', 'Operating hours per year', 'hrs/yr');

            % module_criteria section
            schema(end+1) = tribe.ui.ConfigInspector.makeField('module_criteria.compute_rate_gbp_per_kw_per_month', ...
                'numeric', cfg.module_criteria.compute_rate_gbp_per_kw_per_month, 'non_negative', ...
                [], 'Compute Rate', 'module_criteria', 'Revenue per kW IT capacity per month', 'GBP/kW/month');

            schema(end+1) = tribe.ui.ConfigInspector.makeField('module_criteria.target_utilisation_rate_pct', ...
                'fraction', cfg.module_criteria.target_utilisation_rate_pct, 'fraction', ...
                [], 'Target Utilisation Rate', 'module_criteria', 'Expected capacity utilisation', '%');

            schema(end+1) = tribe.ui.ConfigInspector.makeField('module_criteria.heat_pump_enabled', ...
                'binary', cfg.module_criteria.heat_pump_enabled, 'binary', ...
                [], 'Heat Pump Enabled', 'module_criteria', 'Enable heat pump for temperature uplift', '');

            schema(end+1) = tribe.ui.ConfigInspector.makeField('module_criteria.heat_pump_output_temperature_c', ...
                'numeric', cfg.module_criteria.heat_pump_output_temperature_c, 'positive', ...
                [], 'Heat Pump Output Temperature', 'module_criteria', 'Target delivery temperature with HP', 'C');

            schema(end+1) = tribe.ui.ConfigInspector.makeField('module_criteria.hours_per_year', ...
                'numeric', cfg.module_criteria.hours_per_year, 'positive', ...
                [], 'Hours Per Year', 'module_criteria', 'Annual operating hours for heat', 'hrs/yr');

            schema(end+1) = tribe.ui.ConfigInspector.makeField('module_criteria.base_heat_price_no_hp_gbp_per_mwh', ...
                'numeric', cfg.module_criteria.base_heat_price_no_hp_gbp_per_mwh, 'non_negative', ...
                [], 'Base Heat Price (No HP)', 'module_criteria', 'Heat price without heat pump', 'GBP/MWh');

            schema(end+1) = tribe.ui.ConfigInspector.makeField('module_criteria.premium_heat_price_with_hp_gbp_per_mwh', ...
                'numeric', cfg.module_criteria.premium_heat_price_with_hp_gbp_per_mwh, 'non_negative', ...
                [], 'Premium Heat Price (With HP)', 'module_criteria', 'Heat price with heat pump', 'GBP/MWh');

            schema(end+1) = tribe.ui.ConfigInspector.makeField('module_criteria.reference_industrial_gas_price_gbp_per_mwh', ...
                'numeric', cfg.module_criteria.reference_industrial_gas_price_gbp_per_mwh, 'non_negative', ...
                [], 'Reference Gas Price', 'module_criteria', 'Industrial gas price for comparison', 'GBP/MWh');

            % module_opex section
            schema(end+1) = tribe.ui.ConfigInspector.makeField('module_opex.electricity_rate_gbp_per_kwh', ...
                'numeric', cfg.module_opex.electricity_rate_gbp_per_kwh, 'non_negative', ...
                [], 'Electricity Rate', 'module_opex', 'Operating electricity cost', 'GBP/kWh');

            schema(end+1) = tribe.ui.ConfigInspector.makeField('module_opex.base_maintenance_pct_of_base_capex', ...
                'fraction', cfg.module_opex.base_maintenance_pct_of_base_capex, 'fraction', ...
                [], 'Base Maintenance %', 'module_opex', 'Annual maintenance as % of base capex', '%');

            schema(end+1) = tribe.ui.ConfigInspector.makeField('module_opex.heat_pump_maintenance_pct_of_hp_capex', ...
                'fraction', cfg.module_opex.heat_pump_maintenance_pct_of_hp_capex, 'fraction', ...
                [], 'HP Maintenance %', 'module_opex', 'Annual HP maintenance as % of HP capex', '%');

            schema(end+1) = tribe.ui.ConfigInspector.makeField('module_opex.insurance_pct_of_total_capex', ...
                'fraction', cfg.module_opex.insurance_pct_of_total_capex, 'fraction', ...
                [], 'Insurance %', 'module_opex', 'Annual insurance as % of total capex', '%');

            schema(end+1) = tribe.ui.ConfigInspector.makeField('module_opex.site_lease_per_licence_gbp_per_yr', ...
                'numeric', cfg.module_opex.site_lease_per_licence_gbp_per_yr, 'non_negative', ...
                [], 'Site Lease', 'module_opex', 'Annual site lease cost', 'GBP/yr');

            schema(end+1) = tribe.ui.ConfigInspector.makeField('module_opex.remote_monitoring_noc_gbp_per_yr', ...
                'numeric', cfg.module_opex.remote_monitoring_noc_gbp_per_yr, 'non_negative', ...
                [], 'Remote Monitoring/NOC', 'module_opex', 'Annual monitoring cost', 'GBP/yr');

            schema(end+1) = tribe.ui.ConfigInspector.makeField('module_opex.connectivity_admin_gbp_per_yr', ...
                'numeric', cfg.module_opex.connectivity_admin_gbp_per_yr, 'non_negative', ...
                [], 'Connectivity/Admin', 'module_opex', 'Annual connectivity and admin cost', 'GBP/yr');

            % buyer_profile section
            schema(end+1) = tribe.ui.ConfigInspector.makeField('buyer_profile.process_id', ...
                'enum', cfg.buyer_profile.process_id, '', ...
                tribe.ui.ConfigInspector.getChoices('buyer_profile.process_id'), ...
                'Process', 'buyer_profile', 'Industrial heat process', '');

            schema(end+1) = tribe.ui.ConfigInspector.makeField('buyer_profile.module_footprint_each_m', ...
                'numeric', cfg.buyer_profile.module_footprint_each_m, 'positive', ...
                [], 'Module Footprint', 'buyer_profile', 'Module length/width', 'm');

            schema(end+1) = tribe.ui.ConfigInspector.makeField('buyer_profile.bms_per_controls_package', ...
                'numeric', cfg.buyer_profile.bms_per_controls_package, 'non_negative', ...
                [], 'BMS Per Controls Package', 'buyer_profile', 'BMS units per controls package', '');

            % system section
            schema(end+1) = tribe.ui.ConfigInspector.makeField('system.shared_infrastructure_pct', ...
                'fraction', cfg.system.shared_infrastructure_pct, 'fraction', ...
                [], 'Shared Infrastructure %', 'system', 'Shared infrastructure percentage', '%');

            schema(end+1) = tribe.ui.ConfigInspector.makeField('system.shared_overhead_pct', ...
                'fraction', cfg.system.shared_overhead_pct, 'fraction', ...
                [], 'Shared Overhead %', 'system', 'Shared overhead percentage', '%');

            schema(end+1) = tribe.ui.ConfigInspector.makeField('system.design_velocity_m_per_s', ...
                'numeric', cfg.system.design_velocity_m_per_s, 'positive', ...
                [], 'Design Velocity', 'system', 'Pipe design flow velocity', 'm/s');

            cached = schema;
        end

        function meta = getFieldMeta(field_path)
            %GETFIELDMETA Get metadata for a specific field path.
            schema = tribe.ui.ConfigInspector.getSchema();
            paths = {schema.path};
            idx = find(strcmp(paths, field_path), 1);
            if isempty(idx)
                error('ConfigInspector:NotFound', 'Unknown field path: %s', field_path);
            end
            meta = schema(idx);
        end

        function sections = getSections()
            %GETSECTIONS List all configurable sections.
            sections = ["rack_profile", "module_criteria", "module_opex", "buyer_profile", "system"];
        end

        function fields = getFieldsForSection(section_name)
            %GETFIELDSFORSECTION Get fields for a specific section.
            schema = tribe.ui.ConfigInspector.getSchema();
            mask = strcmp({schema.section}, section_name);
            fields = schema(mask);
        end

        function choices = getChoices(field_path)
            %GETCHOICES Get dropdown choices for enumerable fields.
            switch field_path
                case 'rack_profile.chipset'
                    ref = tribe.data.ReferenceData();
                    choices = ref.chipsets.name;
                case 'rack_profile.cooling_method'
                    ref = tribe.data.ReferenceData();
                    choices = ref.cooling_methods.name;
                case 'buyer_profile.process_id'
                    processes = tribe.data.ProcessLibrary.all();
                    choices = string({processes.dropdown_name});
                otherwise
                    choices = [];
            end
        end

        function field_type = getFieldType(field_path)
            %GETFIELDTYPE Check if field is numeric, string, boolean, or enum.
            meta = tribe.ui.ConfigInspector.getFieldMeta(field_path);
            field_type = meta.type;
        end

        function params = getSweepableParameters()
            %GETSWEEPABLEPARAMETERS Get all numeric config paths for sweeping.
            schema = tribe.ui.ConfigInspector.getSchema();
            mask = ismember({schema.type}, {'numeric', 'fraction'});
            filtered = schema(mask);
            params = string({filtered.path});
        end

        function labels = getSectionLabels()
            %GETSECTIONLABELS Get human-readable labels for sections.
            labels = struct( ...
                'rack_profile', 'Rack Profile', ...
                'module_criteria', 'Module Criteria', ...
                'module_opex', 'Module Opex', ...
                'buyer_profile', 'Buyer Profile', ...
                'system', 'System');
        end
    end

    methods (Static, Access = private)
        function field = makeField(path, type, default, constraints, choices, label, section, description, units)
            %MAKEFIELD Helper to create a field schema entry.
            field = struct( ...
                'path', path, ...
                'type', type, ...
                'default', default, ...
                'constraints', constraints, ...
                'choices', choices, ...
                'label', label, ...
                'section', section, ...
                'description', description, ...
                'units', units);
        end
    end
end
