function test_system_calcs()
%TEST_SYSTEM_CALCS Validate system calculations against the Excel workbook.

validation_dir = fileparts(mfilename('fullpath'));
model_root = fileparts(validation_dir);
repo_root = fileparts(model_root);
excel_path = fullfile(repo_root, 'Tribe_model_20.1.26.xlsx');

addpath(model_root);

inputs = readInputs(excel_path);

rp = tribe.calc.calcRackProfile(inputs.chipset, inputs.cooling_method, ...
    inputs.module_it_target, inputs.electricity_price, inputs.annual_hours);
ref = tribe.data.ReferenceData();
mc = tribe.calc.calcModuleCriteria(rp, inputs.hp_enabled, inputs.hp_output_temp, ...
    inputs.utilisation, inputs.hours_per_year, inputs.base_heat_price, inputs.premium_heat_price);
mcapex = tribe.calc.calcModuleCapex(rp, mc, ref);
mopex = tribe.calc.calcModuleOpex(rp, mc, mcapex, inputs.electricity_rate);
mflow = tribe.calc.calcModuleFlow(mc, rp.cooling_method, ref);
bp = tribe.calc.calcBuyerProfile(rp, mc, mflow, inputs.process_id, ref);

scapex = tribe.calc.calcSystemCapex(mcapex, bp, ref);
sopex = tribe.calc.calcSystemOpex(mopex, bp, ref);
sflow = tribe.calc.calcSystemFlow(mc, bp);
spl = tribe.calc.calcSystemPL(mc, bp, scapex, sopex);

expected = calcExpected(mc, mcapex, mopex, bp, inputs, ref);

[excel_scapex, has_scapex] = readExcelExpectedSystemCapex(excel_path);
[excel_sopex, has_sopex] = readExcelExpectedSystemOpex(excel_path);
[excel_sflow, has_sflow] = readExcelExpectedSystemFlow(excel_path);
[excel_spl, has_spl] = readExcelExpectedSystemPL(excel_path);

if has_scapex
    expected.scapex = mergeExpected(expected.scapex, excel_scapex);
else
    fprintf('System capex validation: Excel formulas not cached; using computed expectations.\n');
end

if has_sopex
    expected.sopex = mergeExpected(expected.sopex, excel_sopex);
else
    fprintf('System opex validation: Excel formulas not cached; using computed expectations.\n');
end

if has_sflow
    expected.sflow = mergeExpected(expected.sflow, excel_sflow);
else
    fprintf('System flow validation: Excel formulas not cached; using computed expectations.\n');
end

if has_spl
    expected.spl = mergeExpected(expected.spl, excel_spl);
else
    fprintf('System P&L validation: Excel formulas not cached; using computed expectations.\n');
end

scapex_fields = [ ...
    "chipset", ...
    "cooling_method", ...
    "gpus_per_module", ...
    "selected_buyer_profile", ...
    "modules_required", ...
    "enclosure_structure", ...
    "cooling_system", ...
    "power_distribution", ...
    "thermal_integration", ...
    "monitoring_controls", ...
    "cooling_method_premium", ...
    "heat_pump_if_enabled", ...
    "total_per_module", ...
    "total_module_capex", ...
    "shared_infrastructure_pct", ...
    "shared_infrastructure_gbp", ...
    "integration_commissioning", ...
    "rejection_capacity_required_kwth", ...
    "rejection_capex_rate_gbp_per_kwth", ...
    "heat_rejection_capex", ...
    "flow_deficit_m3_per_hr", ...
    "augmentation_pumps_required", ...
    "augmentation_pump_capex", ...
    "mixing_valve_controls", ...
    "pipe_upsizing_allowance", ...
    "subtotal_hydraulic_augmentation", ...
    "base_system_capex_excl_rejection", ...
    "heat_rejection_capex__b44", ...
    "hydraulic_augmentation_capex", ...
    "total_system_capex", ...
    "capex_per_it_kw_gbp_per_kw", ...
    "capex_per_kwth_delivered_gbp_per_kwth" ...
    ];

sopex_fields = [ ...
    "chipset", ...
    "cooling_method", ...
    "gpus_per_module", ...
    "selected_buyer_profile", ...
    "modules_in_system", ...
    "electricity_infra_hp", ...
    "maintenance_insurance", ...
    "other_site_noc_admin", ...
    "total_per_module", ...
    "total_module_opex", ...
    "shared_overhead_pct", ...
    "shared_overhead_gbp_per_yr", ...
    "base_system_opex_excl_rejection", ...
    "excess_heat_kwth", ...
    "rejection_running_cost_gbp_per_kwth_per_yr", ...
    "heat_rejection_opex_gbp_per_yr", ...
    "heat_rejection_uplift_pct", ...
    "augmentation_pump_capacity_m3_per_hr", ...
    "augmentation_pump_power_kw", ...
    "annual_operating_hours", ...
    "electricity_rate_gbp_per_kwh", ...
    "augmentation_pump_electricity_gbp_per_yr", ...
    "total_system_opex" ...
    ];

sflow_fields = [ ...
    "chipset", ...
    "cooling_method", ...
    "capture_temperature_c", ...
    "selected_buyer_profile", ...
    "modules_in_system", ...
    "required_temperature_c", ...
    "required_thermal_load_kwth", ...
    "required_flow_rate_m3_per_hr", ...
    "annual_heat_demand_mwh", ...
    "delivery_temperature_c", ...
    "system_thermal_capacity_kwth", ...
    "system_flow_capacity_m3_per_hr", ...
    "annual_heat_supply_mwh", ...
    "temperature_c", ...
    "temperature_c__supplied", ...
    "temperature_c__match", ...
    "thermal_load_kwth", ...
    "thermal_load_kwth__supplied", ...
    "thermal_load_kwth__match", ...
    "flow_rate_m3_per_hr", ...
    "flow_rate_m3_per_hr__supplied", ...
    "flow_rate_m3_per_hr__match", ...
    "annual_energy_mwh", ...
    "annual_energy_mwh__supplied", ...
    "annual_energy_mwh__match", ...
    "thermal_utilisation", ...
    "flow_utilisation", ...
    "binding_constraint", ...
    "spare_capacity_kwth", ...
    "spare_capacity_m3_per_hr", ...
    "design_velocity_m_per_s", ...
    "main_header_pipe_id_mm", ...
    "nearest_dn_size" ...
    ];

spl_fields = [ ...
    "selected_buyer_profile", ...
    "modules_in_system", ...
    "chipset", ...
    "cooling_method", ...
    "module_it_capacity_kw", ...
    "rack_rate_gbp_per_kw_per_month", ...
    "operating_hours_per_year", ...
    "utilisation_assumption_pct", ...
    "compute_revenue_per_module_gbp_per_yr", ...
    "total_compute_revenue_gbp_per_yr", ...
    "heat_price_gbp_per_mwh", ...
    "buyer_operating_hours_per_year", ...
    "theoretical_heat_output_kwth", ...
    "theoretical_heat_revenue_gbp_per_yr", ...
    "actual_buyer_absorption_kwth", ...
    "actual_heat_revenue_gbp_per_yr", ...
    "heat_utilisation_pct", ...
    "lost_heat_revenue_gbp_per_yr", ...
    "compute_revenue_gbp_per_yr", ...
    "heat_revenue_gbp_per_yr", ...
    "total_revenue_gbp_per_yr", ...
    "heat_as_pct_of_total_revenue", ...
    "base_system_opex_gbp_per_yr", ...
    "heat_rejection_opex_gbp_per_yr", ...
    "hydraulic_augmentation_opex_gbp_per_yr", ...
    "total_opex_gbp_per_yr", ...
    "gross_profit_gbp_per_yr", ...
    "gross_margin_pct", ...
    "total_system_capex_gbp", ...
    "simple_payback_years", ...
    "unlevered_roi_pct", ...
    "heat_utilisation_efficiency_pct", ...
    "revenue_lost_to_heat_rejection_gbp_per_yr", ...
    "cost_of_heat_rejection_gbp_per_yr", ...
    "total_heat_inefficiency_cost_gbp_per_yr", ...
    "heat_inefficiency_as_pct_of_potential_profit" ...
    ];

all_pass = true;
for i = 1:numel(scapex_fields)
    field = scapex_fields(i);
    all_pass = checkEqual("scapex." + field, scapex.(field), expected.scapex.(field)) && all_pass;
end

for i = 1:numel(sopex_fields)
    field = sopex_fields(i);
    all_pass = checkEqual("sopex." + field, sopex.(field), expected.sopex.(field)) && all_pass;
end

for i = 1:numel(sflow_fields)
    field = sflow_fields(i);
    all_pass = checkEqual("sflow." + field, sflow.(field), expected.sflow.(field)) && all_pass;
end

for i = 1:numel(spl_fields)
    field = spl_fields(i);
    all_pass = checkEqual("spl." + field, spl.(field), expected.spl.(field)) && all_pass;
end

if all_pass
    fprintf('System calculations validation: PASS\n');
else
    fprintf('System calculations validation: FAIL\n');
end
end

function inputs = readInputs(excel_path)
inputs = struct();

rp_data = readExcelRange(excel_path, '0. Rack Profile', 'B6:B70');
get_rp = @(row) rp_data{row - 5, 1};
inputs.chipset = get_rp(6);
inputs.cooling_method = get_rp(17);
inputs.module_it_target = get_rp(36);
inputs.electricity_price = get_rp(58);
inputs.annual_hours = get_rp(67);

mc_data = readExcelRange(excel_path, '1. Module Criteria', 'B6:B30');
get_mc = @(row) mc_data{row - 6 + 1, 1};
inputs.utilisation = get_mc(7);
inputs.hp_enabled = get_mc(15);
inputs.hp_output_temp = get_mc(16);
inputs.hours_per_year = get_mc(23);
inputs.base_heat_price = get_mc(27);
inputs.premium_heat_price = get_mc(28);

mopex_data = readExcelRange(excel_path, '3. Module Opex', 'B5:B29');
get_mopex = @(row) mopex_data{row - 5 + 1, 1};
inputs.electricity_rate = get_mopex(5);

bp_data = readExcelRange(excel_path, '5. Buyer Profile', 'B11:B11');
inputs.process_id = bp_data{1};

scapex_data = readExcelRange(excel_path, '6. System Capex', 'B25:B25');
inputs.shared_infrastructure_pct = scapex_data{1};

sopex_data = readExcelRange(excel_path, '7. System Opex', 'B21:B21');
inputs.shared_overhead_pct = sopex_data{1};

sflow_data = readExcelRange(excel_path, '8. System Flow', 'B40:B40');
inputs.design_velocity_m_per_s = sflow_data{1};
end

function expected = calcExpected(mc, mcapex, mopex, bp, inputs, ref)
expected = struct();
expected.scapex = struct();
expected.sopex = struct();
expected.sflow = struct();
expected.spl = struct();

shared_infrastructure_pct = coalesceNumeric(inputs.shared_infrastructure_pct, 0.05);
shared_overhead_pct = coalesceNumeric(inputs.shared_overhead_pct, 0.05);
design_velocity_m_per_s = coalesceNumeric(inputs.design_velocity_m_per_s, 2);

expected.scapex.chipset = string(bp.chipset);
expected.scapex.cooling_method = string(bp.cooling_method);
expected.scapex.gpus_per_module = bp.gpus_per_module;
expected.scapex.selected_buyer_profile = string(bp.select_process);
expected.scapex.modules_required = bp.modules_required;
expected.scapex.enclosure_structure = mcapex.subtotal_enclosure;
expected.scapex.cooling_system = mcapex.subtotal_dtc_cooling + mcapex.subtotal_immersion_cooling;
expected.scapex.power_distribution = mcapex.subtotal_power;
expected.scapex.thermal_integration = mcapex.subtotal_thermal;
expected.scapex.monitoring_controls = mcapex.subtotal_monitoring;
expected.scapex.cooling_method_premium = mcapex.applied_to_base_infrastructure;
expected.scapex.heat_pump_if_enabled = mcapex.subtotal_heat_pump;
expected.scapex.total_per_module = mcapex.total_module_capex;
expected.scapex.total_module_capex = expected.scapex.total_per_module * expected.scapex.modules_required;
expected.scapex.shared_infrastructure_pct = shared_infrastructure_pct;
expected.scapex.shared_infrastructure_gbp = expected.scapex.total_module_capex ...
    * expected.scapex.shared_infrastructure_pct;

if expected.scapex.modules_required > 1
    expected.scapex.integration_commissioning = 25000 * (expected.scapex.modules_required - 1);
else
    expected.scapex.integration_commissioning = 0;
end

expected.scapex.rejection_capacity_required_kwth = bp.rejection_capacity_required_kwth;
expected.scapex.rejection_capex_rate_gbp_per_kwth = bp.rejection_capex_rate_gbp_per_kwth;
if expected.scapex.rejection_capacity_required_kwth > 0
    expected.scapex.heat_rejection_capex = expected.scapex.rejection_capacity_required_kwth ...
        * expected.scapex.rejection_capex_rate_gbp_per_kwth;
else
    expected.scapex.heat_rejection_capex = 0;
end

expected.scapex.flow_deficit_m3_per_hr = bp.flow_deficit_m3_per_hr;
expected.scapex.augmentation_pumps_required = bp.augmentation_pumps_required;
expected.scapex.augmentation_pump_capex = expected.scapex.augmentation_pumps_required ...
    * ref.standard_augmentation_pump_capacity_m3_per_hr ...
    * ref.augmentation_pump_capex_gbp_per_m3_per_hr;

if expected.scapex.flow_deficit_m3_per_hr > 0
    expected.scapex.mixing_valve_controls = ref.mixing_valve_controls_gbp;
else
    expected.scapex.mixing_valve_controls = 0;
end

if expected.scapex.flow_deficit_m3_per_hr > 20
    expected.scapex.pipe_upsizing_allowance = expected.scapex.flow_deficit_m3_per_hr ...
        * ref.pipe_upsizing_allowance_gbp_per_m3_per_hr;
else
    expected.scapex.pipe_upsizing_allowance = 0;
end

expected.scapex.subtotal_hydraulic_augmentation = sum([expected.scapex.augmentation_pump_capex, ...
    expected.scapex.mixing_valve_controls, expected.scapex.pipe_upsizing_allowance]);

expected.scapex.base_system_capex_excl_rejection = expected.scapex.total_module_capex ...
    + expected.scapex.shared_infrastructure_gbp + expected.scapex.integration_commissioning;
expected.scapex.heat_rejection_capex__b44 = expected.scapex.heat_rejection_capex;
expected.scapex.hydraulic_augmentation_capex = expected.scapex.subtotal_hydraulic_augmentation;
expected.scapex.total_system_capex = expected.scapex.base_system_capex_excl_rejection ...
    + expected.scapex.heat_rejection_capex__b44 + expected.scapex.hydraulic_augmentation_capex;
expected.scapex.capex_per_it_kw_gbp_per_kw = expected.scapex.total_system_capex ...
    / (expected.scapex.modules_required * mcapex.module_it_capacity_kw);
expected.scapex.capex_per_kwth_delivered_gbp_per_kwth = expected.scapex.total_system_capex ...
    / bp.heat_demand_kwth;

expected.sopex.chipset = string(bp.chipset);
expected.sopex.cooling_method = string(bp.cooling_method);
expected.sopex.gpus_per_module = bp.gpus_per_module;
expected.sopex.selected_buyer_profile = string(bp.select_process);
expected.sopex.modules_in_system = bp.modules_required;
expected.sopex.electricity_infra_hp = mopex.subtotal_electricity;
expected.sopex.maintenance_insurance = mopex.subtotal_maintenance_insurance;
expected.sopex.other_site_noc_admin = mopex.subtotal_other;
expected.sopex.total_per_module = mopex.total_module_opex_gbp_per_yr;
expected.sopex.total_module_opex = expected.sopex.total_per_module * expected.sopex.modules_in_system;
expected.sopex.shared_overhead_pct = shared_overhead_pct;
expected.sopex.shared_overhead_gbp_per_yr = expected.sopex.total_module_opex ...
    * expected.sopex.shared_overhead_pct;
expected.sopex.base_system_opex_excl_rejection = expected.sopex.total_module_opex ...
    + expected.sopex.shared_overhead_gbp_per_yr;

expected.sopex.excess_heat_kwth = bp.excess_heat_kwth;
expected.sopex.rejection_running_cost_gbp_per_kwth_per_yr = bp.rejection_opex_rate_gbp_per_kwth_per_yr;
if expected.sopex.excess_heat_kwth > 0
    expected.sopex.heat_rejection_opex_gbp_per_yr = expected.sopex.excess_heat_kwth ...
        * expected.sopex.rejection_running_cost_gbp_per_kwth_per_yr;
else
    expected.sopex.heat_rejection_opex_gbp_per_yr = 0;
end

if expected.sopex.base_system_opex_excl_rejection > 0
    expected.sopex.heat_rejection_uplift_pct = expected.sopex.heat_rejection_opex_gbp_per_yr ...
        / expected.sopex.base_system_opex_excl_rejection;
else
    expected.sopex.heat_rejection_uplift_pct = 0;
end

expected.sopex.augmentation_pump_capacity_m3_per_hr = bp.augmentation_pump_capacity_m3_per_hr;
expected.sopex.augmentation_pump_power_kw = bp.augmentation_pump_power_kw;
expected.sopex.annual_operating_hours = bp.operating_hours_per_year;
expected.sopex.electricity_rate_gbp_per_kwh = mopex.electricity_rate_gbp_per_kwh;
expected.sopex.augmentation_pump_electricity_gbp_per_yr = expected.sopex.augmentation_pump_power_kw ...
    * expected.sopex.annual_operating_hours * expected.sopex.electricity_rate_gbp_per_kwh;
expected.sopex.total_system_opex = expected.sopex.base_system_opex_excl_rejection ...
    + expected.sopex.heat_rejection_opex_gbp_per_yr ...
    + expected.sopex.augmentation_pump_electricity_gbp_per_yr;

expected.sflow.chipset = string(bp.chipset);
expected.sflow.cooling_method = string(bp.cooling_method);
expected.sflow.capture_temperature_c = mc.capture_temperature_c;
expected.sflow.selected_buyer_profile = string(bp.select_process);
expected.sflow.modules_in_system = bp.modules_required;
expected.sflow.required_temperature_c = bp.required_temperature_c;
expected.sflow.required_thermal_load_kwth = bp.heat_demand_kwth;
expected.sflow.required_flow_rate_m3_per_hr = bp.required_flow_rate_m3_per_hr;
expected.sflow.annual_heat_demand_mwh = bp.annual_heat_demand_mwh;
expected.sflow.delivery_temperature_c = mc.delivery_temperature_c;
expected.sflow.system_thermal_capacity_kwth = bp.system_thermal_capacity_kwth;
expected.sflow.system_flow_capacity_m3_per_hr = bp.system_flow_capacity_m3_per_hr;
expected.sflow.annual_heat_supply_mwh = expected.sflow.system_thermal_capacity_kwth ...
    * bp.operating_hours_per_year / 1000;
expected.sflow.temperature_c = expected.sflow.required_temperature_c;
expected.sflow.temperature_c__supplied = expected.sflow.delivery_temperature_c;
expected.sflow.temperature_c__match = temperatureMatch(expected.sflow.temperature_c, ...
    expected.sflow.temperature_c__supplied);

expected.sflow.thermal_load_kwth = expected.sflow.required_thermal_load_kwth;
expected.sflow.thermal_load_kwth__supplied = expected.sflow.system_thermal_capacity_kwth;
expected.sflow.thermal_load_kwth__match = spareOrShort(expected.sflow.thermal_load_kwth__supplied, ...
    expected.sflow.thermal_load_kwth, "kWth", 0);

expected.sflow.flow_rate_m3_per_hr = expected.sflow.required_flow_rate_m3_per_hr;
expected.sflow.flow_rate_m3_per_hr__supplied = expected.sflow.system_flow_capacity_m3_per_hr;
expected.sflow.flow_rate_m3_per_hr__match = spareOrShort(expected.sflow.flow_rate_m3_per_hr__supplied, ...
    expected.sflow.flow_rate_m3_per_hr, flowUnit(), 1);

expected.sflow.annual_energy_mwh = expected.sflow.annual_heat_demand_mwh;
expected.sflow.annual_energy_mwh__supplied = expected.sflow.annual_heat_supply_mwh;
expected.sflow.annual_energy_mwh__match = spareOrShort(expected.sflow.annual_energy_mwh__supplied, ...
    expected.sflow.annual_energy_mwh, "MWh", 0);

expected.sflow.thermal_utilisation = bp.thermal_utilisation_pct;
expected.sflow.flow_utilisation = bp.flow_utilisation_pct;
expected.sflow.binding_constraint = bindingConstraint(bp.thermal_utilisation_pct, bp.flow_utilisation_pct);
expected.sflow.spare_capacity_kwth = expected.sflow.system_thermal_capacity_kwth ...
    - expected.sflow.required_thermal_load_kwth;
expected.sflow.spare_capacity_m3_per_hr = expected.sflow.system_flow_capacity_m3_per_hr ...
    - expected.sflow.required_flow_rate_m3_per_hr;
expected.sflow.design_velocity_m_per_s = design_velocity_m_per_s;
expected.sflow.main_header_pipe_id_mm = sqrt((expected.sflow.required_flow_rate_m3_per_hr / 3600) ...
    / (expected.sflow.design_velocity_m_per_s * 3.14159 / 4)) * 1000;
expected.sflow.nearest_dn_size = nearestDN(expected.sflow.main_header_pipe_id_mm);

expected.spl.selected_buyer_profile = string(bp.select_process);
expected.spl.modules_in_system = bp.modules_required;
expected.spl.chipset = string(bp.chipset);
expected.spl.cooling_method = string(bp.cooling_method);
expected.spl.module_it_capacity_kw = mc.module_it_capacity_kw;
expected.spl.rack_rate_gbp_per_kw_per_month = mc.compute_rate_gbp_per_kw_per_month;
expected.spl.operating_hours_per_year = bp.operating_hours_per_year;
expected.spl.utilisation_assumption_pct = mc.target_utilisation_rate_pct;
expected.spl.compute_revenue_per_module_gbp_per_yr = expected.spl.module_it_capacity_kw ...
    * expected.spl.rack_rate_gbp_per_kw_per_month * 12 * expected.spl.utilisation_assumption_pct;
expected.spl.total_compute_revenue_gbp_per_yr = expected.spl.compute_revenue_per_module_gbp_per_yr ...
    * expected.spl.modules_in_system;
expected.spl.heat_price_gbp_per_mwh = mc.effective_heat_price_gbp_per_mwh;
expected.spl.buyer_operating_hours_per_year = bp.operating_hours_per_year;
expected.spl.theoretical_heat_output_kwth = bp.system_heat_generation_kwth;
expected.spl.theoretical_heat_revenue_gbp_per_yr = expected.spl.theoretical_heat_output_kwth ...
    * expected.spl.buyer_operating_hours_per_year * expected.spl.heat_price_gbp_per_mwh / 1000;
expected.spl.actual_buyer_absorption_kwth = bp.buyer_heat_absorption_kwth;
expected.spl.actual_heat_revenue_gbp_per_yr = expected.spl.actual_buyer_absorption_kwth ...
    * expected.spl.buyer_operating_hours_per_year * expected.spl.heat_price_gbp_per_mwh / 1000;
if expected.spl.theoretical_heat_output_kwth > 0
    expected.spl.heat_utilisation_pct = expected.spl.actual_buyer_absorption_kwth ...
        / expected.spl.theoretical_heat_output_kwth;
else
    expected.spl.heat_utilisation_pct = 0;
end
expected.spl.lost_heat_revenue_gbp_per_yr = expected.spl.theoretical_heat_revenue_gbp_per_yr ...
    - expected.spl.actual_heat_revenue_gbp_per_yr;
expected.spl.compute_revenue_gbp_per_yr = expected.spl.total_compute_revenue_gbp_per_yr;
expected.spl.heat_revenue_gbp_per_yr = expected.spl.actual_heat_revenue_gbp_per_yr;
expected.spl.total_revenue_gbp_per_yr = expected.spl.compute_revenue_gbp_per_yr ...
    + expected.spl.heat_revenue_gbp_per_yr;
if expected.spl.total_revenue_gbp_per_yr > 0
    expected.spl.heat_as_pct_of_total_revenue = expected.spl.heat_revenue_gbp_per_yr ...
        / expected.spl.total_revenue_gbp_per_yr;
else
    expected.spl.heat_as_pct_of_total_revenue = 0;
end
expected.spl.base_system_opex_gbp_per_yr = expected.sopex.base_system_opex_excl_rejection;
expected.spl.heat_rejection_opex_gbp_per_yr = expected.sopex.heat_rejection_opex_gbp_per_yr;
expected.spl.hydraulic_augmentation_opex_gbp_per_yr = expected.sopex.augmentation_pump_electricity_gbp_per_yr;
expected.spl.total_opex_gbp_per_yr = expected.sopex.total_system_opex;
expected.spl.gross_profit_gbp_per_yr = expected.spl.total_revenue_gbp_per_yr ...
    - expected.spl.total_opex_gbp_per_yr;
if expected.spl.total_revenue_gbp_per_yr > 0
    expected.spl.gross_margin_pct = expected.spl.gross_profit_gbp_per_yr ...
        / expected.spl.total_revenue_gbp_per_yr;
else
    expected.spl.gross_margin_pct = 0;
end
expected.spl.total_system_capex_gbp = expected.scapex.total_system_capex;
if expected.spl.gross_profit_gbp_per_yr > 0
    expected.spl.simple_payback_years = expected.spl.total_system_capex_gbp ...
        / expected.spl.gross_profit_gbp_per_yr;
else
    expected.spl.simple_payback_years = 0;
end
if expected.spl.total_system_capex_gbp > 0
    expected.spl.unlevered_roi_pct = expected.spl.gross_profit_gbp_per_yr ...
        / expected.spl.total_system_capex_gbp;
else
    expected.spl.unlevered_roi_pct = 0;
end
expected.spl.heat_utilisation_efficiency_pct = expected.spl.heat_utilisation_pct;
expected.spl.revenue_lost_to_heat_rejection_gbp_per_yr = expected.spl.lost_heat_revenue_gbp_per_yr;
expected.spl.cost_of_heat_rejection_gbp_per_yr = expected.spl.heat_rejection_opex_gbp_per_yr;
expected.spl.total_heat_inefficiency_cost_gbp_per_yr = expected.spl.revenue_lost_to_heat_rejection_gbp_per_yr ...
    + expected.spl.cost_of_heat_rejection_gbp_per_yr;
if (expected.spl.gross_profit_gbp_per_yr + expected.spl.total_heat_inefficiency_cost_gbp_per_yr) > 0
    expected.spl.heat_inefficiency_as_pct_of_potential_profit = expected.spl.total_heat_inefficiency_cost_gbp_per_yr ...
        / (expected.spl.gross_profit_gbp_per_yr + expected.spl.total_heat_inefficiency_cost_gbp_per_yr);
else
    expected.spl.heat_inefficiency_as_pct_of_potential_profit = 0;
end
end

function [expected, has_excel_values] = readExcelExpectedSystemCapex(excel_path)
data = readExcelRange(excel_path, '6. System Capex', 'B5:B49');
get_cell = @(row) data{row - 5 + 1, 1};

sentinel_rows = [21, 24, 46];
has_excel_values = hasValues(get_cell, sentinel_rows);

mapping = { ...
    'chipset', 5, 1; ...
    'cooling_method', 6, 1; ...
    'gpus_per_module', 7, 1; ...
    'selected_buyer_profile', 10, 1; ...
    'modules_required', 11, 1; ...
    'enclosure_structure', 14, 1; ...
    'cooling_system', 15, 1; ...
    'power_distribution', 16, 1; ...
    'thermal_integration', 17, 1; ...
    'monitoring_controls', 18, 1; ...
    'cooling_method_premium', 19, 1; ...
    'heat_pump_if_enabled', 20, 1; ...
    'total_per_module', 21, 1; ...
    'total_module_capex', 24, 1; ...
    'shared_infrastructure_pct', 25, 1; ...
    'shared_infrastructure_gbp', 26, 1; ...
    'integration_commissioning', 27, 1; ...
    'rejection_capacity_required_kwth', 30, 1; ...
    'rejection_capex_rate_gbp_per_kwth', 31, 1; ...
    'heat_rejection_capex', 32, 1; ...
    'flow_deficit_m3_per_hr', 35, 1; ...
    'augmentation_pumps_required', 36, 1; ...
    'augmentation_pump_capex', 37, 1; ...
    'mixing_valve_controls', 38, 1; ...
    'pipe_upsizing_allowance', 39, 1; ...
    'subtotal_hydraulic_augmentation', 40, 1; ...
    'base_system_capex_excl_rejection', 43, 1; ...
    'heat_rejection_capex__b44', 44, 1; ...
    'hydraulic_augmentation_capex', 45, 1; ...
    'total_system_capex', 46, 1; ...
    'capex_per_it_kw_gbp_per_kw', 48, 1; ...
    'capex_per_kwth_delivered_gbp_per_kwth', 49, 1 ...
    };

expected = readMappedCells(data, 5, mapping);
end

function [expected, has_excel_values] = readExcelExpectedSystemOpex(excel_path)
data = readExcelRange(excel_path, '7. System Opex', 'B5:B37');
get_cell = @(row) data{row - 5 + 1, 1};

sentinel_rows = [17, 23, 37];
has_excel_values = hasValues(get_cell, sentinel_rows);

mapping = { ...
    'chipset', 5, 1; ...
    'cooling_method', 6, 1; ...
    'gpus_per_module', 7, 1; ...
    'selected_buyer_profile', 10, 1; ...
    'modules_in_system', 11, 1; ...
    'electricity_infra_hp', 14, 1; ...
    'maintenance_insurance', 15, 1; ...
    'other_site_noc_admin', 16, 1; ...
    'total_per_module', 17, 1; ...
    'total_module_opex', 20, 1; ...
    'shared_overhead_pct', 21, 1; ...
    'shared_overhead_gbp_per_yr', 22, 1; ...
    'base_system_opex_excl_rejection', 23, 1; ...
    'excess_heat_kwth', 26, 1; ...
    'rejection_running_cost_gbp_per_kwth_per_yr', 27, 1; ...
    'heat_rejection_opex_gbp_per_yr', 28, 1; ...
    'heat_rejection_uplift_pct', 29, 1; ...
    'augmentation_pump_capacity_m3_per_hr', 31, 1; ...
    'augmentation_pump_power_kw', 32, 1; ...
    'annual_operating_hours', 33, 1; ...
    'electricity_rate_gbp_per_kwh', 34, 1; ...
    'augmentation_pump_electricity_gbp_per_yr', 35, 1; ...
    'total_system_opex', 37, 1 ...
    };

expected = readMappedCells(data, 5, mapping);
end

function [expected, has_excel_values] = readExcelExpectedSystemFlow(excel_path)
data = readExcelRange(excel_path, '8. System Flow', 'B5:D42');
get_cell = @(row) data{row - 5 + 1, 1};

sentinel_rows = [21, 23, 41];
has_excel_values = hasValues(get_cell, sentinel_rows);

mapping = { ...
    'chipset', 5, 1; ...
    'cooling_method', 6, 1; ...
    'capture_temperature_c', 7, 1; ...
    'selected_buyer_profile', 10, 1; ...
    'modules_in_system', 11, 1; ...
    'required_temperature_c', 14, 1; ...
    'required_thermal_load_kwth', 15, 1; ...
    'required_flow_rate_m3_per_hr', 16, 1; ...
    'annual_heat_demand_mwh', 17, 1; ...
    'delivery_temperature_c', 20, 1; ...
    'system_thermal_capacity_kwth', 21, 1; ...
    'system_flow_capacity_m3_per_hr', 22, 1; ...
    'annual_heat_supply_mwh', 23, 1; ...
    'temperature_c', 26, 1; ...
    'temperature_c__supplied', 26, 2; ...
    'temperature_c__match', 26, 3; ...
    'thermal_load_kwth', 27, 1; ...
    'thermal_load_kwth__supplied', 27, 2; ...
    'thermal_load_kwth__match', 27, 3; ...
    'flow_rate_m3_per_hr', 28, 1; ...
    'flow_rate_m3_per_hr__supplied', 28, 2; ...
    'flow_rate_m3_per_hr__match', 28, 3; ...
    'annual_energy_mwh', 29, 1; ...
    'annual_energy_mwh__supplied', 29, 2; ...
    'annual_energy_mwh__match', 29, 3; ...
    'thermal_utilisation', 32, 1; ...
    'flow_utilisation', 33, 1; ...
    'binding_constraint', 34, 1; ...
    'spare_capacity_kwth', 36, 1; ...
    'spare_capacity_m3_per_hr', 37, 1; ...
    'design_velocity_m_per_s', 40, 1; ...
    'main_header_pipe_id_mm', 41, 1; ...
    'nearest_dn_size', 42, 1 ...
    };

expected = readMappedCells(data, 5, mapping);
end

function [expected, has_excel_values] = readExcelExpectedSystemPL(excel_path)
data = readExcelRange(excel_path, '9. System P&L', 'B6:B57');
get_cell = @(row) data{row - 6 + 1, 1};

sentinel_rows = [17, 35, 45, 57];
has_excel_values = hasValues(get_cell, sentinel_rows);

mapping = { ...
    'selected_buyer_profile', 6, 1; ...
    'modules_in_system', 7, 1; ...
    'chipset', 8, 1; ...
    'cooling_method', 9, 1; ...
    'module_it_capacity_kw', 12, 1; ...
    'rack_rate_gbp_per_kw_per_month', 13, 1; ...
    'operating_hours_per_year', 14, 1; ...
    'utilisation_assumption_pct', 15, 1; ...
    'compute_revenue_per_module_gbp_per_yr', 16, 1; ...
    'total_compute_revenue_gbp_per_yr', 17, 1; ...
    'heat_price_gbp_per_mwh', 20, 1; ...
    'buyer_operating_hours_per_year', 21, 1; ...
    'theoretical_heat_output_kwth', 23, 1; ...
    'theoretical_heat_revenue_gbp_per_yr', 24, 1; ...
    'actual_buyer_absorption_kwth', 26, 1; ...
    'actual_heat_revenue_gbp_per_yr', 27, 1; ...
    'heat_utilisation_pct', 29, 1; ...
    'lost_heat_revenue_gbp_per_yr', 30, 1; ...
    'compute_revenue_gbp_per_yr', 33, 1; ...
    'heat_revenue_gbp_per_yr', 34, 1; ...
    'total_revenue_gbp_per_yr', 35, 1; ...
    'heat_as_pct_of_total_revenue', 36, 1; ...
    'base_system_opex_gbp_per_yr', 39, 1; ...
    'heat_rejection_opex_gbp_per_yr', 40, 1; ...
    'hydraulic_augmentation_opex_gbp_per_yr', 41, 1; ...
    'total_opex_gbp_per_yr', 42, 1; ...
    'gross_profit_gbp_per_yr', 45, 1; ...
    'gross_margin_pct', 46, 1; ...
    'total_system_capex_gbp', 48, 1; ...
    'simple_payback_years', 49, 1; ...
    'unlevered_roi_pct', 50, 1; ...
    'heat_utilisation_efficiency_pct', 53, 1; ...
    'revenue_lost_to_heat_rejection_gbp_per_yr', 54, 1; ...
    'cost_of_heat_rejection_gbp_per_yr', 55, 1; ...
    'total_heat_inefficiency_cost_gbp_per_yr', 56, 1; ...
    'heat_inefficiency_as_pct_of_potential_profit', 57, 1 ...
    };

expected = readMappedCells(data, 6, mapping);
end

function expected = readMappedCells(data, start_row, mapping)
expected = struct();
for i = 1:size(mapping, 1)
    field = mapping{i, 1};
    row = mapping{i, 2};
    col = mapping{i, 3};
    value = data{row - start_row + 1, col};
    if isFormulaValue(value) || ismissingValue(value)
        continue;
    end
    expected.(field) = value;
end
end

function tf = hasValues(get_cell, rows)
tf = false;
for i = 1:numel(rows)
    value = get_cell(rows(i));
    if isFormulaValue(value) || ismissingValue(value)
        continue;
    end
    if isnumeric(value)
        if any(~isnan(value), 'all') && any(abs(value) > 0, 'all')
            tf = true;
            return;
        end
    elseif (isstring(value) || ischar(value)) && strlength(string(value)) > 0
        tf = true;
        return;
    end
end
end

function ok = checkEqual(label, expected, actual)
if isstring(expected) || ischar(expected)
    ok = isequal(string(expected), string(actual));
elseif isnumeric(expected)
    ok = isnumeric(actual) && isequal(size(expected), size(actual)) ...
        && all(abs(expected - actual) < 1e-9, 'all');
else
    ok = isequaln(expected, actual);
end

if ok
    fprintf('PASS: %s\n', label);
else
    fprintf('FAIL: %s | expected: %s | actual: %s\n', label, valueToString(expected), valueToString(actual));
end
end

function data = readExcelRange(excel_path, sheet, range)
try
    data = readcell(excel_path, 'Sheet', sheet, 'Range', range, 'UseExcel', true);
catch
    data = readcell(excel_path, 'Sheet', sheet, 'Range', range);
end
end

function tf = isFormulaValue(value)
tf = (ischar(value) || isstring(value)) && startsWith(string(value), "=");
end

function tf = ismissingValue(value)
tf = isempty(value) ...
    || (isstring(value) && all(ismissing(value))) ...
    || (isnumeric(value) && any(isnan(value), 'all'));
end

function value = coalesceNumeric(value, fallback)
if isempty(value)
    value = fallback;
elseif isnumeric(value) && any(isnan(value), 'all')
    value = fallback;
end
end

function text = temperatureMatch(required_c, supplied_c)
check_symbol = char(10003);
cross_symbol = char(10007);
degree_symbol = char(176);
if supplied_c >= required_c
    text = string(check_symbol) + " YES";
else
    text = string(cross_symbol) + " NO - need " + string(required_c) ...
        + string(degree_symbol) + "C";
end
end

function text = spareOrShort(supplied, required, unit, digits)
check_symbol = char(10003);
cross_symbol = char(10007);
if supplied >= required
    spare_value = round(supplied - required, digits);
    text = string(check_symbol) + " YES - " + string(spare_value) + " " + unit + " spare";
else
    short_value = round(required - supplied, digits);
    text = string(cross_symbol) + " SHORT " + string(short_value) + " " + unit;
end
end

function unit = flowUnit()
m3_symbol = char(179);
unit = "m" + string(m3_symbol) + "/hr";
end

function text = bindingConstraint(thermal_utilisation, flow_utilisation)
if isnumber(thermal_utilisation) && isnumber(flow_utilisation)
    if thermal_utilisation >= flow_utilisation
        text = "Thermal";
    else
        text = "Flow";
    end
else
    text = "-";
end
end

function tf = isnumber(value)
tf = isnumeric(value) && isscalar(value) && ~isnan(value);
end

function dn = nearestDN(pipe_id_mm)
if pipe_id_mm < 28
    dn = "DN25";
elseif pipe_id_mm < 36
    dn = "DN32";
elseif pipe_id_mm < 42
    dn = "DN40";
elseif pipe_id_mm < 54
    dn = "DN50";
elseif pipe_id_mm < 68
    dn = "DN65";
elseif pipe_id_mm < 82
    dn = "DN80";
elseif pipe_id_mm < 107
    dn = "DN100";
elseif pipe_id_mm < 131
    dn = "DN125";
elseif pipe_id_mm < 159
    dn = "DN150";
else
    dn = "DN200+";
end
end

function text = valueToString(value)
if isstring(value) || ischar(value)
    text = char(string(value));
elseif isnumeric(value)
    text = mat2str(value);
else
    text = '<unprintable>';
end
end

function expected = mergeExpected(expected, excel_expected)
fields = fieldnames(excel_expected);
for i = 1:numel(fields)
    field = fields{i};
    expected.(field) = excel_expected.(field);
end
end
