classdef ProcessLibrary
    %PROCESSLIBRARY Static access to industrial process reference data.
    % Fields: required_temp_c (C), heat_demand_kwth (kWth),
    % operating_hours_per_year (hrs/yr), delta_t_c (C).

    methods (Static)
        function process = getProcess(process_id)
            processes = tribe.data.ProcessLibrary.all();
            ids = string({processes.dropdown_name});
            idx = find(ids == string(process_id), 1);
            if isempty(idx)
                error('ProcessLibrary:NotFound', 'Unknown process_id: %s', process_id);
            end
            process = rmfield(processes(idx), 'dropdown_name');
        end

        function processes = all()
            persistent cached
            if isempty(cached)
                cached = tribe.data.ProcessLibrary.build_();
            end
            processes = cached;
        end
    end

    methods (Static, Access = private)
        function processes = build_()
            u = struct('uuml', char(252), 'sup2', char(178), 'sup3', char(179), 'emdash', char(8212));
            durr_systems = "D" + u.uuml + "rr Systems AG";
            durr_paint = "D" + u.uuml + "rr Paint Systems";
            joinery_small = "Joinery/furniture (5m" + u.sup3 + ")";
            sawmill_small = "Small sawmill (25m" + u.sup3 + ")";
            kiln_industrial = "Industrial kiln (100m" + u.sup3 + ")";
            office_small = "Small office (1,000m" + u.sup2 + ")";
            office_large = "Large office (5,000m" + u.sup2 + ")";
            kensa_url = "https://www.kensaheatpumps.com/wp-content/uploads/2014/09/AIS" + u.emdash + ...
                "Heat-pumps-and-swimming-pools-" + u.emdash + "2.0_with_metadata.pdf";

            processes = struct( ...
                'name', {
                    "Pasteurisation",
                    "Pasteurisation",
                    "Pasteurisation",
                    "CIP (Clean-in-Place)",
                    "CIP (Clean-in-Place)",
                    "CIP (Clean-in-Place)",
                    "Bottle washing",
                    "Bottle washing",
                    "Bottle washing",
                    "Parts degreasing",
                    "Parts degreasing",
                    "Parts degreasing",
                    "Commercial laundry",
                    "Commercial laundry",
                    "Commercial laundry",
                    "Timber drying",
                    "Timber drying",
                    "Timber drying",
                    "Paint curing",
                    "Paint curing",
                    "Paint curing",
                    "Textile drying",
                    "Textile drying",
                    "Textile drying",
                    "District heating",
                    "District heating",
                    "District heating",
                    "Building HVAC",
                    "Building HVAC",
                    "Building HVAC",
                    "Swimming pool",
                    "Swimming pool",
                    "Swimming pool",
                    "Glasshouse heating",
                    "Glasshouse heating",
                    "Glasshouse heating",
                    "Reactor heating",
                    "Reactor heating",
                    "Reactor heating",
                    "Fermentation",
                    "Fermentation",
                    "Fermentation"
                }, ...
                'size_category', {
                    "Small",
                    "Medium",
                    "Large",
                    "Small",
                    "Medium",
                    "Large",
                    "Small",
                    "Medium",
                    "Large",
                    "Small",
                    "Medium",
                    "Large",
                    "Small",
                    "Medium",
                    "Large",
                    "Small",
                    "Medium",
                    "Large",
                    "Small",
                    "Medium",
                    "Large",
                    "Small",
                    "Medium",
                    "Large",
                    "Small",
                    "Medium",
                    "Large",
                    "Small",
                    "Medium",
                    "Large",
                    "Small",
                    "Medium",
                    "Large",
                    "Small",
                    "Medium",
                    "Large",
                    "Small",
                    "Medium",
                    "Large",
                    "Small",
                    "Medium",
                    "Large"
                }, ...
                'required_temp_c', {
                    72,
                    72,
                    72,
                    85,
                    85,
                    85,
                    80,
                    80,
                    80,
                    60,
                    60,
                    60,
                    70,
                    70,
                    70,
                    70,
                    70,
                    70,
                    80,
                    80,
                    80,
                    90,
                    90,
                    90,
                    70,
                    70,
                    70,
                    60,
                    60,
                    60,
                    30,
                    30,
                    30,
                    50,
                    50,
                    50,
                    90,
                    90,
                    90,
                    35,
                    35,
                    35
                }, ...
                'heat_demand_kwth', {
                    65,
                    500,
                    2500,
                    50,
                    150,
                    400,
                    35,
                    120,
                    280,
                    25,
                    75,
                    180,
                    130,
                    670,
                    2700,
                    50,
                    200,
                    500,
                    50,
                    150,
                    350,
                    60,
                    200,
                    450,
                    500,
                    2000,
                    5000,
                    80,
                    300,
                    1000,
                    60,
                    180,
                    450,
                    200,
                    750,
                    2000,
                    60,
                    200,
                    450,
                    25,
                    100,
                    280
                }, ...
                'operating_hours_per_year', {
                    4000,
                    5500,
                    7000,
                    3000,
                    4000,
                    5000,
                    4000,
                    5500,
                    7000,
                    3000,
                    4500,
                    6000,
                    4000,
                    5500,
                    7000,
                    5000,
                    6000,
                    7000,
                    3000,
                    4500,
                    6000,
                    4000,
                    5500,
                    7000,
                    4500,
                    5000,
                    5500,
                    3500,
                    4000,
                    4500,
                    6000,
                    7000,
                    8000,
                    3500,
                    4000,
                    4500,
                    5000,
                    6000,
                    7000,
                    6000,
                    7000,
                    8000
                }, ...
                'notes', {
                    "Craft dairy/microbrewery (5,000 L/day)",
                    "Regional dairy (50,000 L/day)",
                    "Industrial dairy (250,000+ L/day)",
                    "Single vessel/tank system",
                    "Multi-tank dairy/brewery",
                    "Full processing plant",
                    "Craft bottling line",
                    "Regional bottler (10k bottles/hr)",
                    "Industrial (50k+ bottles/hr)",
                    "Workshop/small batch",
                    "Automotive supplier",
                    "Heavy manufacturing",
                    "Hotel (500 kg/day)",
                    "Hospital (2,500 kg/day)",
                    "Industrial (10,000+ kg/day)",
                    joinery_small,
                    sawmill_small,
                    kiln_industrial,
                    "Small paint shop",
                    "Automotive components",
                    "OEM paint line",
                    "Small finishing mill",
                    "Regional mill",
                    "Industrial stenter line",
                    "100-200 homes",
                    "400-800 homes",
                    "1,000+ homes",
                    office_small,
                    office_large,
                    "Campus/hospital",
                    "Hotel pool (12x6m)",
                    "Leisure centre (25m)",
                    "Competition (50m)",
                    "1 hectare tomatoes",
                    "4 hectares mixed",
                    "10+ hectares",
                    "Pilot/R&D reactor",
                    "Batch chemical",
                    "Continuous process",
                    "Craft brewery (5k hl/yr)",
                    "Regional (50k hl/yr)",
                    "Industrial biotech"
                }, ...
                'dropdown_name', {
                    "Pasteurisation - Small",
                    "Pasteurisation - Medium",
                    "Pasteurisation - Large",
                    "CIP (Clean-in-Place) - Small",
                    "CIP (Clean-in-Place) - Medium",
                    "CIP (Clean-in-Place) - Large",
                    "Bottle washing - Small",
                    "Bottle washing - Medium",
                    "Bottle washing - Large",
                    "Parts degreasing - Small",
                    "Parts degreasing - Medium",
                    "Parts degreasing - Large",
                    "Commercial laundry - Small",
                    "Commercial laundry - Medium",
                    "Commercial laundry - Large",
                    "Timber drying - Small",
                    "Timber drying - Medium",
                    "Timber drying - Large",
                    "Paint curing - Small",
                    "Paint curing - Medium",
                    "Paint curing - Large",
                    "Textile drying - Small",
                    "Textile drying - Medium",
                    "Textile drying - Large",
                    "District heating - Small",
                    "District heating - Medium",
                    "District heating - Large",
                    "Building HVAC - Small",
                    "Building HVAC - Medium",
                    "Building HVAC - Large",
                    "Swimming pool - Small",
                    "Swimming pool - Medium",
                    "Swimming pool - Large",
                    "Glasshouse heating - Small",
                    "Glasshouse heating - Medium",
                    "Glasshouse heating - Large",
                    "Reactor heating - Small",
                    "Reactor heating - Medium",
                    "Reactor heating - Large",
                    "Fermentation - Small",
                    "Fermentation - Medium",
                    "Fermentation - Large"
                }, ...
                'source', {
                    "Tetra Pak Dairy Processing Handbook",
                    "Tetra Pak Dairy Processing Handbook",
                    "Tetra Pak Dairy Processing Handbook",
                    "CSI Designs - Heat Exchangers in CIP",
                    "CSI Designs - Heat Exchangers in CIP",
                    "CSI Designs - Heat Exchangers in CIP",
                    "GEA Brewing Systems",
                    "GEA Brewing Systems",
                    "GEA Brewing Systems",
                    durr_systems,
                    durr_systems,
                    durr_systems,
                    "AERCO Laundry Sizing Guide",
                    "AERCO Laundry Sizing Guide",
                    "AERCO Laundry Sizing Guide",
                    "Oklahoma State Extension - Kiln Drying",
                    "Oklahoma State Extension - Kiln Drying",
                    "Oklahoma State Extension - Kiln Drying",
                    durr_paint,
                    durr_paint,
                    durr_paint,
                    "Monforts Textilmaschinen",
                    "Monforts Textilmaschinen",
                    "Monforts Textilmaschinen",
                    "CIBSE CP1 Heat Networks Code of Practice",
                    "CIBSE CP1 Heat Networks Code of Practice",
                    "CIBSE CP1 Heat Networks Code of Practice",
                    "ASHRAE 90.1 / CIBSE Guide B",
                    "ASHRAE 90.1 / CIBSE Guide B",
                    "ASHRAE 90.1 / CIBSE Guide B",
                    "Kensa Heat Pumps - Pools Application Guide",
                    "Kensa Heat Pumps - Pools Application Guide",
                    "Kensa Heat Pumps - Pools Application Guide",
                    "Dutch Greenhouses / AHDB Horticulture",
                    "Dutch Greenhouses / AHDB Horticulture",
                    "Dutch Greenhouses / AHDB Horticulture",
                    "IChemE Process Data",
                    "IChemE Process Data",
                    "IChemE Process Data",
                    "Clarke Energy / Brewery Best Practice",
                    "Clarke Energy / Brewery Best Practice",
                    "Clarke Energy / Brewery Best Practice"
                }, ...
                'delta_t_c', {
                    5,
                    5,
                    5,
                    12,
                    12,
                    12,
                    10,
                    10,
                    10,
                    15,
                    15,
                    15,
                    18,
                    18,
                    18,
                    18,
                    18,
                    18,
                    15,
                    15,
                    15,
                    20,
                    20,
                    20,
                    30,
                    30,
                    30,
                    12,
                    12,
                    12,
                    5,
                    5,
                    5,
                    20,
                    20,
                    20,
                    10,
                    10,
                    10,
                    5,
                    5,
                    5
                }, ...
                'source_url', {
                    "https://dairyprocessinghandbook.tetrapak.com/chapter/heat-exchangers",
                    "https://dairyprocessinghandbook.tetrapak.com/chapter/heat-exchangers",
                    "https://dairyprocessinghandbook.tetrapak.com/chapter/heat-exchangers",
                    "https://www.csidesigns.com/blog/articles/how-heat-exchangers-work-during-clean-in-place",
                    "https://www.csidesigns.com/blog/articles/how-heat-exchangers-work-during-clean-in-place",
                    "https://www.csidesigns.com/blog/articles/how-heat-exchangers-work-during-clean-in-place",
                    "https://www.gea.com/en/products/brewery-systems",
                    "https://www.gea.com/en/products/brewery-systems",
                    "https://www.gea.com/en/products/brewery-systems",
                    "https://www.durr.com/en/products-and-services/cleaning-technology",
                    "https://www.durr.com/en/products-and-services/cleaning-technology",
                    "https://www.durr.com/en/products-and-services/cleaning-technology",
                    "https://www.aerco.com/dfsmedia/0533dbba17714b1ab581ab07a4cbb521/58930-source/sizing-laundry-hot-water-systems",
                    "https://www.aerco.com/dfsmedia/0533dbba17714b1ab581ab07a4cbb521/58930-source/sizing-laundry-hot-water-systems",
                    "https://www.aerco.com/dfsmedia/0533dbba17714b1ab581ab07a4cbb521/58930-source/sizing-laundry-hot-water-systems",
                    "https://extension.okstate.edu/fact-sheets/fundamental-aspects-of-kiln-drying-lumber.html",
                    "https://extension.okstate.edu/fact-sheets/fundamental-aspects-of-kiln-drying-lumber.html",
                    "https://extension.okstate.edu/fact-sheets/fundamental-aspects-of-kiln-drying-lumber.html",
                    "https://www.durr.com/en/products-and-services/paint-systems",
                    "https://www.durr.com/en/products-and-services/paint-systems",
                    "https://www.durr.com/en/products-and-services/paint-systems",
                    "https://www.monforts.de/en/",
                    "https://www.monforts.de/en/",
                    "https://www.monforts.de/en/",
                    "https://www.cibsejournal.com/technical/the-perfect-return-heat-network-return-temperatures/",
                    "https://www.cibsejournal.com/technical/the-perfect-return-heat-network-return-temperatures/",
                    "https://www.cibsejournal.com/technical/the-perfect-return-heat-network-return-temperatures/",
                    "https://www.trane.com/content/dam/Trane/Commercial/global/products-systems/education-training/engineers-newsletters/standards-codes/ADM-APN070-EN_06032019.pdf",
                    "https://www.trane.com/content/dam/Trane/Commercial/global/products-systems/education-training/engineers-newsletters/standards-codes/ADM-APN070-EN_06032019.pdf",
                    "https://www.trane.com/content/dam/Trane/Commercial/global/products-systems/education-training/engineers-newsletters/standards-codes/ADM-APN070-EN_06032019.pdf",
                    kensa_url,
                    kensa_url,
                    kensa_url,
                    "https://dutchgreenhouses.com/en/climate/heating",
                    "https://dutchgreenhouses.com/en/climate/heating",
                    "https://dutchgreenhouses.com/en/climate/heating",
                    "https://www.icheme.org/",
                    "https://www.icheme.org/",
                    "https://www.icheme.org/",
                    "https://www.clarke-energy.com/applications/breweries/",
                    "https://www.clarke-energy.com/applications/breweries/",
                    "https://www.clarke-energy.com/applications/breweries/"
                });
        end
    end
end
